name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Specify the Node.js version

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Lockfile Verification
        run: |
          git diff --exit-code package-lock.json || echo "Lockfile has changed!"

      - name: Run Linting
        run: |
          pnpm run lint

      - name: Build Application
        run: |
          pnpm run build

      - name: Run Tests
        run: |
          pnpm run test
